name: genlocale
on:
  push:
    branches:
      - main
jobs:
  genlocale:
    name: genlocale
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Run locale generation
        run: |
          python3 i18n/scan_i18n.py
          cd i18n
          python3 locale_diff.py

      - name: Commit back
        if: ${{ !github.head_ref }}
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "üé® ÂêåÊ≠• locale"

      - name: Create Pull Request
        if: ${{ !github.head_ref }}
        continue-on-error: true
        uses: peter-evans/create-pull-request@v4
  
