name: genlocale
on: [ push ]
jobs:
  golangci:
    name: genlocale
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Run locale generation
        run: |
          python3 extract_locale.py
          cd locale
          python3 locale_diff.py

      - name: Commit back
        if: ${{ !github.head_ref }}
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "üé® ÂêåÊ≠• locale"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
